name: Example app

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: example

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Get project Flutter version 🏷️
        id: fvm-config
        uses: kuhnroyal/flutter-fvm-config-action@v1.2.0

      - name: Setup Flutter 💻
        id: setup-flutter
        uses: subosito/flutter-action@v2.22.0
        with:
          flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ steps.fvm-config.outputs.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Cache Pub 💾
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup-flutter.outputs.CACHE-PATH }}
            **/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Run linting 🧪
        run: |
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
