name: Pull request target actions

on:
  pull_request_target:

jobs:
  pull-request:
    uses: zeshuaro/github-actions-workflows/.github/workflows/pull-request-target.yml@4d59d30b8b50bfa00610adb7d061bf5ab17f048a # main
